from rest_framework import serializers
from .models import Student

class StudentSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Student
        # 'url' is a default field generated by HyperlinkedModelSerializer
        fields = ['id', 'url', 'name', 'roll', 'city']
